name: RSS to Notion
on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 允许手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 使用最新的 checkout 版本

      - name: RSS to Notion
        uses: p-nerd/rss-to-notion@master
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          rss_url: ${{ secrets.RSS_URL }}
